#ifndef LEDS_H
#define LEDS_H

#include "Board.h"

#define MCU_LED1_ON() GPIO_HIGH(MCU_LED1_PORT, MCU_LED1_BIT)
#define MCU_LED1_OFF() GPIO_LOW(MCU_LED1_PORT, MCU_LED1_BIT)

#define MCU_LED2_ON() GPIO_HIGH(MCU_LED2_PORT, MCU_LED2_BIT)
#define MCU_LED2_OFF() GPIO_LOW(MCU_LED2_PORT, MCU_LED2_BIT)

#define DRAIN_LED_ON() GPIO_HIGH(DRAIN_LED_PORT, DRAIN_LED_BIT)
#define DRAIN_LED_OFF() GPIO_LOW(DRAIN_LED_PORT, DRAIN_LED_BIT)

#define POWER_LED_ON() GPIO_HIGH(POWER_LED_PORT, POWER_LED_BIT)
#define POWER_LED_OFF() GPIO_LOW(POWER_LED_PORT, POWER_LED_BIT)

void leds_init()
{
	GPIO_OUTPUT(MCU_LED1_DDR, MCU_LED1_BIT);
	GPIO_OUTPUT(MCU_LED2_DDR, MCU_LED2_BIT);
	GPIO_OUTPUT(DRAIN_LED_DDR, DRAIN_LED_BIT);
	GPIO_OUTPUT(POWER_LED_DDR, POWER_LED_BIT);
}

#endif /* LEDS_H */
