#ifndef POWER_H
#define POWER_H

#include "Board.h"

#define PWR_PRECHARGE_5V_ON()         GPIO_HIGH(PRECHARGE_5V_PORT, PRECHARGE_5V_BIT)
#define PWR_PRECHARGE_5V_OFF()        GPIO_LOW(PRECHARGE_5V_PORT, PRECHARGE_5V_BIT)

#define PWR_5V_ON()                GPIO_HIGH(PWR_EN_5V_PORT, PWR_EN_5V_BIT)
#define PWR_5V_OFF()               GPIO_LOW(PWR_EN_5V_PORT, PWR_EN_5V_BIT)

#define PWR_6V5_SERVO_ON()         GPIO_HIGH(PWR_EN_6V5_SERVO_PORT, PWR_EN_6V5_SERVO_BIT)
#define PWR_6V5_SERVO_OFF()        GPIO_LOW(PWR_EN_6V5_SERVO_PORT, PWR_EN_6V5_SERVO_BIT)

#define PWR_12V_ON()               GPIO_HIGH(PWR_EN_12V_PORT, PWR_EN_12V_BIT)
#define PWR_12V_OFF()              GPIO_LOW(PWR_EN_12V_PORT, PWR_EN_12V_BIT)

static inline void power_init()
{
    GPIO_OUTPUT(PRECHARGE_5V_DDR, PRECHARGE_5V_BIT);
    GPIO_OUTPUT(PWR_EN_5V_DDR, PWR_EN_5V_BIT);
    GPIO_OUTPUT(PWR_EN_6V5_SERVO_DDR, PWR_EN_6V5_SERVO_BIT);
    GPIO_OUTPUT(PWR_EN_12V_DDR, PWR_EN_12V_BIT);

    GPIO_LOW(PRECHARGE_5V_PORT, PRECHARGE_5V_BIT);
    GPIO_LOW(PWR_EN_5V_PORT, PWR_EN_5V_BIT);
    GPIO_LOW(PWR_EN_6V5_SERVO_PORT, PWR_EN_6V5_SERVO_BIT);
    GPIO_LOW(PWR_EN_12V_PORT, PWR_EN_12V_BIT);
}

#endif  /* POWER_H */